export const beforeEventCategoryCleaner = () => {
  const restaurantCategories = [
    { alias: 'afghani', label: 'Afghani'},
    { alias: 'african', label: 'African'},
    { alias: 'newamerican', label: 'New American'},
    { alias: 'tradamerican', label: 'Traditional American'},
    { alias: 'brazilian', label: 'Brazilian'},
    { alias: 'burgers', label: 'Burgers'},
    { alias: 'chinese', label: 'Chinese'},
    { alias: 'french', label: 'French'},
    { alias: 'irish', label: 'Irish'},
    { alias: 'italian', label: 'Italian'},
    { alias: 'pizza', label: 'Pizza'},
    { alias: 'ramen', label: 'Ramen'},
    { alias: 'seafood', label: 'Seafood'}
  ];

  return restaurantCategories;
};


// andalusian, [IT, ES])
// arabian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// arabpizza, [BR])
// argentine, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// armenian, [CZ, TR, PL, AR, FR, GB, IT, US, ES, BE])
// Asian Fusion (asianfusion, All)
// Asturian (asturian, [ES])
// Australian (australian, All)
// Austrian (austrian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Baguettes (baguettes, [DE, CZ, TR, MX, NO, PT, IT, SE])
// Bangladeshi (bangladeshi, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Barbeque (bbq, [AR, AT, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Basque (basque, [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
// Bavarian (bavarian, [DE, AT, CH])
// Beer Garden (beergarden, [DE, AT, CZ, CH])
// Beer Hall (beerhall, [DE, AT, CH])
// Beisl (beisl, [AT])
// Belgian (belgian, All)
// Flemish (flemish, [FR])
// Bistros (bistros, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW])
// Black Sea (blacksea, [TR])
// Brasseries (brasseries, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Brazilian (brazilian, All)
// Brazilian Empanadas (brazilianempanadas, [BR])
// Central Brazilian (centralbrazilian, [BR])
// Northeastern Brazilian (northeasternbrazilian, [BR])
// Northern Brazilian (northernbrazilian, [BR])
// Rodizios (rodizios, [AR, PT, BR])
// Breakfast & Brunch (breakfast_brunch, All)
// British (british, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Buffets (buffets, All)
// Bulgarian (bulgarian, [AR, AT, AU, BE, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, PH, PL, PT, SE, TW, US])
// Burgers (burgers, All)
// Burmese (burmese, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Cafes (cafes, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Themed Cafes (themedcafes, [DE, SG, PL, JP, PH, FR, NL, TW, FI, MY, US, HK, BE])
// Cafeteria (cafeteria, [AR, AT, AU, BE, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IT, JP, MX, MY, NL, NO, PH, PL, PT, TR, TW, US])
// Cajun/Creole (cajun, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TR, TW, US])
// Cambodian (cambodian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Canadian (New) (newcanadian, [CA])
// Canteen (canteen, [DE, CZ, CH, PL, JP, DK, NO, IT, NL, FI, AT, BE])
// Caribbean (caribbean, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Dominican (dominican, [US])
// Haitian (haitian, [US, CA])
// Puerto Rican (puertorican, [US])
// Trinidadian (trinidadian, [US])
// Catalan (catalan, [TR, AR, FR, MX, PT, IT, US, ES, CL])
// Cheesesteaks (cheesesteaks, [NL, AU, US, PL, IE, CA, GB])
// Chicken Shop (chickenshop, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Chicken Wings (chicken_wings, [AR, AT, AU, BR, CA, CZ, DE, GB, HK, IE, MX, MY, NZ, PH, PL, SE, SG, TR, TW, US])
// Chilean (chilean, [FI, CL, FR, BR])
// Chinese (chinese, All)
// Cantonese (cantonese, [AU, SG, GB, FR, TW, MY, HK, BE, NZ, JP, AR, IT, NL, SE, US, CA])
// Congee (congee, [MY, HK, SG, TW])
// Dim Sum (dimsum, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Fuzhou (fuzhou, [MY, HK, SG, TW])
// Hainan (hainan, [SG, MY, US, HK, PH])
// Hakka (hakka, [TW, SG, MY, HK, PH, CA])
// Henghwa (henghwa, [MY, HK, SG, TW])
// Hokkien (hokkien, [MY, HK, SG, TW])
// Hunan (hunan, [TW, SG, MY, HK, FR])
// Pekinese (pekinese, [IT, TW, SG, MY, HK, JP, FR])
// Shanghainese (shanghainese, [AU, SG, JP, FR, IT, TW, SE, MY, US, HK, BE])
// Szechuan (szechuan, [AU, SG, JP, FR, GB, TW, MY, US, HK, IE, NZ])
// Teochew (teochew, [MY, HK, SG, TW])
// Comfort Food (comfortfood, [MX, FI, US, JP, AR, CL, CA])
// Corsican (corsican, [FR, BE])
// Creperies (creperies, All)
// Cuban (cuban, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
// Curry Sausage (currysausage, [DE, AT, CH])
// Cypriot (cypriot, [DE, AT, CH])
// Czech (czech, [DE, CZ, AU, PL, GB, FR, DK, NO, IT, FI, SE, US, IE, CA, BE])
// Czech/Slovakian (czechslovakian, [AR, MX, PT])
// Danish (danish, [SE, NO, FR, DK])
// Delis (delis, [AR, AT, AU, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, JP, MX, MY, NO, NZ, PH, PL, SG, TR, TW, US])
// Diners (diners, [AR, AT, BE, BR, CA, CH, CL, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SG, TR, TW, US])
// Dinner Theater (dinnertheater, [AR, AT, AU, BR, CA, CH, CL, CZ, DE, DK, ES, FI, GB, HK, IE, MX, MY, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Dumplings (dumplings, [JP])
// Eastern European (eastern_european, [NO, CZ, AU, FR, DK])
// Ethiopian (ethiopian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, TW, US])
// Fast Food (hotdogs, All)
// Filipino (filipino, [AR, AT, AU, BE, BR, CA, CH, CL, DE, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
// Fischbroetchen (fischbroetchen, [DE])
// Fish & Chips (fishnchips, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
// Flatbread (flatbread, [DE, CH, PL, AT, DK])
// Fondue (fondue, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Food Court (food_court, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PT, SE, SG, US])
// Food Stands (foodstands, All)
// Freiduria (freiduria, [AR, MX, CL, ES])
// French (french, All)
// Alsatian (alsatian, [DE, FR])
// Auvergnat (auvergnat, [FR])
// Berrichon (berrichon, [FR])
// Bourguignon (bourguignon, [FR])
// Mauritius (mauritius, [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
// Nicoise (nicois, [FR])
// Provencal (provencal, [FR])
// Reunion (reunion, [BE, CA, CZ, ES, FI, FR, GB, HK, IE, IT, MY, NL, PH, PT, SE, SG, TW, US])
// French Southwest (sud_ouest, [FR, BE])
// Galician (galician, [PT, ES])
// Game Meat (gamemeat, [AT, AU, BE, CH, CZ, DE, DK, ES, FR, GB, IE, IT, NL, NO, NZ, PL, SE, SG, US])
// Gastropubs (gastropubs, All)
// Georgian (georgian, [DE, CZ, CH, PL, GB, FI, US, AT])
// German (german, All)
// Baden (baden, [DE])
// Eastern German (easterngerman, [DE])
// Franconian (franconian, [DE])
// Hessian (hessian, [DE])
// Northern German (northerngerman, [DE])
// Palatine (palatine, [DE])
// Rhinelandian (rhinelandian, [DE])
// Giblets (giblets, [TR])
// Gluten-Free (gluten_free, All)
// Greek (greek, All)
// Guamanian (guamanian, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, GB, HK, IE, IT, MY, NL, NO, NZ, PH, PT, SE, SG, TW, US])
// Halal (halal, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Hawaiian (hawaiian, [AR, AT, BE, BR, CA, CH, CL, DE, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Heuriger (heuriger, [AT])
// Himalayan/Nepalese (himalayan, All)
// Honduran (honduran, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
// Hong Kong Style Cafe (hkcafe, [US, HK, CA, TW])
// Hot Dogs (hotdog, All)
// Hot Pot (hotpot, [SG, JP, PH, FR, BR, TW, SE, MY, US, HK, CA])
// Hungarian (hungarian, All)
// Iberian (iberian, [US, PT, CA])
// Indian (indpak, All)
// Indonesian (indonesian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// International (international, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, JP, MX, NL, NO, NZ, PL, PT, SE, SG, TW])
// Irish (irish, All)
// Island Pub (island_pub, [SE])
// Israeli (israeli, [DE, AT, CZ, CH])
// Italian (italian, All)
// Abruzzese (abruzzese, [IT])
// Altoatesine (altoatesine, [IT])
// Apulian (apulian, [IT, FR])
// Calabrian (calabrian, [US, IT, FR])
// Cucina campana (cucinacampana, [IT])
// Emilian (emilian, [IT])
// Friulan (friulan, [IT])
// Ligurian (ligurian, [IT, FR])
// Lumbard (lumbard, [IT])
// Napoletana (napoletana, [CZ, IT, FR])
// Piemonte (piemonte, [IT, FR])
// Roman (roman, [IT, FR, JP])
// Sardinian (sardinian, [US, IT, FR])
// Sicilian (sicilian, [CZ, IT, US, PL, FR])
// Tuscan (tuscan, [US, IT, FR])
// Venetian (venetian, [IT, FR])
// Japanese (japanese, All)
// Blowfish (blowfish, [JP])
// Conveyor Belt Sushi (conveyorsushi, [DE, SG, CH, PL, JP, IT, NL, TW, SE, US, HK, AT, BE])
// Donburi (donburi, [HK, JP, TW])
// Gyudon (gyudon, [JP])
// Oyakodon (oyakodon, [JP])
// Hand Rolls (handrolls, [BR, TW])
// Horumon (horumon, [JP, TW])
// Izakaya (izakaya, [AU, SG, JP, BR, MX, TW, US, HK, NZ])
// Japanese Curry (japacurry, [TW, SG, US, HK, JP])
// Kaiseki (kaiseki, [JP, TW])
// Kushikatsu (kushikatsu, [JP])
// Oden (oden, [JP, TW])
// Okinawan (okinawan, [JP])
// Okonomiyaki (okonomiyaki, [JP, TW])
// Onigiri (onigiri, [JP, TW])
// Ramen (ramen, All)
// Robatayaki (robatayaki, [HK, JP, TW])
// Soba (soba, [JP, TW])
// Sukiyaki (sukiyaki, [JP, TW])
// Takoyaki (takoyaki, [JP, TW])
// Tempura (tempura, [SG, JP, TW])
// Teppanyaki (teppanyaki, [AU, SG, JP, MX, TW, US, HK, NZ])
// Tonkatsu (tonkatsu, [SG, JP, TW])
// Udon (udon, [NO, TW, FI, SE, HK, JP, DK])
// Unagi (unagi, [JP, TW])
// Western Style Japanese Food (westernjapanese, [SG, JP, TW])
// Yakiniku (yakiniku, [SG, JP, TW])
// Yakitori (yakitori, [SG, JP, TW])
// Jewish (jewish, [DE, PL, IT])
// Kebab (kebab, All)
// Kopitiam (kopitiam, [MY, SG])
// Korean (korean, All)
// Kosher (kosher, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Kurdish (kurdish, [NO, SE])
// Laos (laos, [AU])
// Laotian (laotian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Latin American (latin, All)
// Colombian (colombian, [AR, FR, MX, FI, US, ES, CL, CA, BE])
// Salvadoran (salvadoran, [US, CA])
// Venezuelan (venezuelan, [PT, US, ES, AR, CL, CA, FR])
// Live/Raw Food (raw_food, All)
// Lyonnais (lyonnais, [FR, BE])
// Malaysian (malaysian, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Mamak (mamak, [MY, AU])
// Nyonya (nyonya, [MY, AU])
// Meatballs (meatballs, [FR, TR, BE, NL])
// Mediterranean (mediterranean, All)
// Falafel (falafel, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
// Mexican (mexican, All)
// Eastern Mexican (easternmexican, [MX])
// Jaliscan (jaliscan, [MX])
// Northern Mexican (northernmexican, [MX])
// Oaxacan (oaxacan, [MX])
// Pueblan (pueblan, [MX])
// Tacos (tacos, [US, MX])
// Tamales (tamales, [MX])
// Yucatan (yucatan, [MX])
// Middle Eastern (mideastern, [AR, AT, AU, BE, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Egyptian (egyptian, [IT, BE, US, CA, FR])
// Lebanese (lebanese, [AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, IE, IT, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Milk Bars (milkbars, [AU, PL])
// Modern Australian (modern_australian, [AU])
// Modern European (modern_european, All)
// Mongolian (mongolian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Moroccan (moroccan, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
// New Mexican Cuisine (newmexican, [US])
// New Zealand (newzealand, [NZ])
// Nicaraguan (nicaraguan, [AT, AU, BE, BR, CA, CH, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Night Food (nightfood, [NO, TR, SE, PL, DK])
// Nikkei (nikkei, [MX, ES, AR, CL, BR])
// Noodles (noodles, [AR, AU, BE, BR, CA, CL, CZ, DK, ES, FI, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Norcinerie (norcinerie, [IT])
// Open Sandwiches (opensandwiches, [NO, TR, SE, DK])
// Oriental (oriental, [DE, PT, CH, AT, FR])
// PF/Comercial (pfcomercial, [BR])
// Pakistani (pakistani, All)
// Pan Asian (panasian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Parent Cafes (eltern_cafes, [DE, AT, CH])
// Parma (parma, [AU])
// Persian/Iranian (persian, All)
// Peruvian (peruvian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, TW, US])
// Pita (pita, [TR])
// Pizza (pizza, All)
// Polish (polish, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
// Pierogis (pierogis, [PL])
// Polynesian (polynesian, [US])
// Pop-Up Restaurants (popuprestaurants, [DE, AU, SG, GB, FR, TW, MY, HK, IE, BE, NZ, PH, DK, NO, NL, SE, US, CA])
// Portuguese (portuguese, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Alentejo (alentejo, [PT])
// Algarve (algarve, [PT])
// Azores (azores, [PT])
// Beira (beira, [PT])
// Fado Houses (fado_houses, [PT])
// Madeira (madeira, [PT])
// Minho (minho, [PT])
// Ribatejo (ribatejo, [PT])
// Tras-os-Montes (tras_os_montes, [PT])
// Potatoes (potatoes, [DE, AT, AU, CH])
// Poutineries (poutineries, [US, CA])
// Pub Food (pubfood, [AU])
// Rice (riceshop, [TR, JP])
// Romanian (romanian, [DE, CZ, CH, PL, FR, ES, AT, BE])
// Rotisserie Chicken (rotisserie_chicken, [AU, PL, AR, FR, BR, MX, PT, IT, NL, ES, CL, BE, NZ])
// Russian (russian, All)
// Salad (salad, All)
// Sandwiches (sandwiches, All)
// Scandinavian (scandinavian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
// Schnitzel (schnitzel, [DE, AT, PL, CH])
// Scottish (scottish, [DE, CH, US, IE, AT, CA, GB])
// Seafood (seafood, All)
// Serbo Croatian (serbocroatian, [DE, CZ, CH, PL, AR, FR, IT, SE, CL, AT, BE])
// Signature Cuisine (signature_cuisine, [AR, DK, MX, NO, PT, SE, ES, CL])
// Singaporean (singaporean, [AR, AT, AU, BE, BR, CA, CH, CL, DE, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Slovakian (slovakian, [CZ, AU, PL, FR, GB, IT, US, IE, CA, BE])
// Soul Food (soulfood, [PL, GB, NO, NL, SE, US, ES, IE, CA])
// Soup (soup, All)
// Southern (southern, [TR, PL, GB, NL, SE, US, IE, CA, NZ])
// Spanish (spanish, All)
// Arroceria / Paella (arroceria_paella, [ES])
// Sri Lankan (srilankan, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, ES, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TR, TW, US])
// Steakhouses (steak, All)
// Supper Clubs (supperclubs, [ES, US, CA, GB])
// Sushi Bars (sushi, All)
// Swabian (swabian, [DE, AT, CH])
// Swedish (swedish, [SE])
// Swiss Food (swissfood, [DE, MX, CZ, CH, ES, AR, CL])
// Syrian (syrian, All)
// Tabernas (tabernas, [PT, TR, ES])
// Taiwanese (taiwanese, [AR, AT, AU, BE, BR, CA, CH, CL, DE, DK, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TW, US])
// Tapas Bars (tapas, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, DK, ES, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, TR, TW, US])
// Tapas/Small Plates (tapasmallplates, All)
// Tavola Calda (tavolacalda, [IT])
// Tex-Mex (tex-mex, [AR, AT, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, SE, SG, TR, TW, US])
// Thai (thai, All)
// Traditional Norwegian (norwegian, [NO, FR])
// Traditional Swedish (traditional_swedish, [FI, SE])
// Trattorie (trattorie, [IT, CH, PL, AR, CL, FR])
// Turkish (turkish, All)
// Chee Kufta (cheekufta, [DE, TR])
// Gozleme (gozleme, [TR])
// Homemade Food (homemadefood, [TR])
// Lahmacun (lahmacun, [TR])
// Ottoman Cuisine (ottomancuisine, [TR])
// Turkish Ravioli (turkishravioli, [TR])
// Ukrainian (ukrainian, [AR, AT, AU, BE, BR, CA, CH, CL, CZ, DE, FI, FR, GB, HK, IE, IT, JP, MX, MY, NL, NO, NZ, PH, PL, PT, SE, SG, TW, US])
// Uzbek (uzbek, [US, CZ])
// Vegan (vegan, All)
// Vegetarian (vegetarian, All)
// Venison (venison, [CZ, AU, SG, PL, GB, DK, NO, IT, IE, CA, NZ])
// Vietnamese (vietnamese, All)
// Waffles (waffles, All)
// Wok (wok, [AT, BE, CH, CL, CZ, DE, DK, ES, FI, FR, MX, MY, NL, NO, PH, PT, SE])
// Wraps (wraps, [NO, CZ, PT, TR, SE, US, DK])
// Yugoslav (yug